version: '3.7'

services:
  web:
    container_name: spotweb_nginx
    image: nginx:latest
    ports:
      - 127.0.0.1:80:80
    volumes:
      - ./spotweb:/spotweb
      - ./spotweb.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped
    depends_on:
      - php
# Remove the next line if you use SQLite database rather than PostgreSQL
      - db

  php:
    container_name: spotweb_php
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./spotweb:/spotweb

# Remove everything below this line
# if you use SQLite database rather than PostgreSQL

  db:
    image: postgres:12.0-alpine
    container_name: spotweb_db
    volumes:
      - ./postgres:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=spotweb
      - POSTGRES_PASSWORD=spotweb
      - POSTGRES_DB=spotweb
    expose:
      - 5432
    restart: unless-stopped
